In [ ]:
# Libraries importation and initial exploration

import pandas as pd

In [ ]:
file_path_life = '/content/life_expc_vlc.csv'
df_life = pd.read_csv(file_path_life, delimiter=';')

df_life.sample(6)

      id   Año   Sexo           Distrito  Valor Fecha creacion  Fecha baja
39   143  2015  Ambos            PATRAIX  83.36     2023-07-02         NaN
152  182  2017  Ambos          EXTRAMURS  84.02     2023-07-02         NaN
68   234  2019  Ambos   POBLATS MARITIMS  82.33     2023-07-02         NaN
96    22  2009  Ambos   POBLATS DEL NORD  82.13     2023-07-02         NaN
282  283  2021  Ambos          BENICALAP  83.98     2023-07-02         NaN
169  218  2018  Ambos  POBLATS DE L'OEST  83.67     2023-07-02         NaN

In [ ]:
df_life.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              286 non-null    int64
 1   Año             286 non-null    int64
 2   Sexo            286 non-null    object
 3   Distrito        286 non-null    object
 4   Valor           286 non-null    float64
 5   Fecha creacion  286 non-null    object
 6   Fecha baja      0 non-null      float64
dtypes: float64(2), int64(2), object(3)
memory usage: 15.8+ KB

In [ ]:
#exploring null values
df_life['Distrito'].isnull().sum()

0

In [ ]:
#exploring duplicated values
df_life['Distrito'].duplicated().sum()

267

In [ ]:
df_life.loc[df_life['Distrito'] == "POBLATS DE L'OEST"]

      id   Año   Sexo           Distrito  Valor Fecha creacion  Fecha baja
11    43  2010  Ambos  POBLATS DE L'OEST  81.44     2023-07-02         NaN
13    65  2011  Ambos  POBLATS DE L'OEST  81.42     2023-07-02         NaN
34   130  2014  Ambos  POBLATS DE L'OEST  81.80     2023-07-02         NaN
50   174  2016  Ambos  POBLATS DE L'OEST  82.16     2023-07-02         NaN
51   175  2016  Ambos  POBLATS DE L'OEST  82.52     2023-07-02         NaN
77   262  2020  Ambos  POBLATS DE L'OEST  83.26     2023-07-02         NaN
94    20  2009  Ambos  POBLATS DE L'OEST  80.76     2023-07-02         NaN
95    21  2009  Ambos  POBLATS DE L'OEST  81.51     2023-07-02         NaN
106   42  2010  Ambos  POBLATS DE L'OEST  80.68     2023-07-02         NaN
119   87  2012  Ambos  POBLATS DE L'OEST  82.09     2023-07-02         NaN
133  131  2014  Ambos  POBLATS DE L'OEST  82.37     2023-07-02         NaN
142  153  2015  Ambos  POBLATS DE L'OEST  82.80     2023-07-02         NaN
160  196  2017  Ambos  POBLATS DE L'OEST  82.75     2023-07-02         NaN
161  197  2017  Ambos  POBLATS DE L'OEST  82.71     2023-07-02         NaN
169  218  2018  Ambos  POBLATS DE L'OEST  83.67     2023-07-02         NaN
170  219  2018  Ambos  POBLATS DE L'OEST  83.33     2023-07-02         NaN
182  263  2020  Ambos  POBLATS DE L'OEST  82.81     2023-07-02         NaN
209   64  2011  Ambos  POBLATS DE L'OEST  81.03     2023-07-02         NaN
216   86  2012  Ambos  POBLATS DE L'OEST  81.62     2023-07-02         NaN
228  108  2013  Ambos  POBLATS DE L'OEST  81.25     2023-07-02         NaN
229  109  2013  Ambos  POBLATS DE L'OEST  82.12     2023-07-02         NaN
236  152  2015  Ambos  POBLATS DE L'OEST  82.16     2023-07-02         NaN
263  240  2019  Ambos  POBLATS DE L'OEST  83.51     2023-07-02         NaN
264  241  2019  Ambos  POBLATS DE L'OEST  83.21     2023-07-02         NaN
283  284  2021  Ambos  POBLATS DE L'OEST  83.85     2023-07-02         NaN
284  285  2021  Ambos  POBLATS DE L'OEST  83.32     2023-07-02         NaN

In [ ]:
# Exploration of unique values in different columns
sorted(df_life['Año'].unique())

[2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]

In [ ]:
sorted(df_life['Sexo'].unique())

['Ambos', 'Hombres', 'Mujeres']

In [ ]:
sorted(df_life['Distrito'].unique())

['ALGIROS',
 'BENICALAP',
 'BENIMACLET',
 'CAMINS AL GRAU',
 'CAMPANAR',
 'CIUTAT VELLA',
 'EL PLA DEL REAL',
 'EXTRAMURS',
 'JESUS',
 "L'EIXAMPLE",
 "L'OLIVERETA",
 'LA SAIDIA',
 'PATRAIX',
 "POBLATS DE L'OEST",
 'POBLATS DEL NORD',
 'POBLATS MARITIMS',
 'QUATRE CARRERES',
 'RASCANYA',
 'Todos']

In [ ]:
# Exploration of minimum values
df_life['Valor'].min()

78.04

In [ ]:
# Exploration of maximum values
df_life['Valor'].max()

86.51

In [ ]:
# Exploration of 'Todos' value per district.
# It happens to be a gender bias but only for values ​​assigned as 'Todos' per district.
df_life.loc[df_life['Distrito'] == 'Todos']

      id   Año     Sexo Distrito  Valor Fecha creacion  Fecha baja
5     23  2010    Ambos    Todos  81.73     2023-07-02         NaN
6     25  2010  Mujeres    Todos  84.67     2023-07-02         NaN
14    67  2012    Ambos    Todos  82.14     2023-07-02         NaN
15    68  2012  Hombres    Todos  78.85     2023-07-02         NaN
16    69  2012  Mujeres    Todos  85.03     2023-07-02         NaN
22    90  2013  Hombres    Todos  79.40     2023-07-02         NaN
27   112  2014  Hombres    Todos  79.72     2023-07-02         NaN
35   134  2015  Hombres    Todos  79.83     2023-07-02         NaN
36   135  2015  Mujeres    Todos  85.37     2023-07-02         NaN
57   199  2018    Ambos    Todos  83.32     2023-07-02         NaN
58   201  2018  Mujeres    Todos  85.89     2023-07-02         NaN
64   221  2019    Ambos    Todos  83.54     2023-07-02         NaN
65   222  2019  Hombres    Todos  80.63     2023-07-02         NaN
71   243  2020    Ambos    Todos  83.09     2023-07-02         NaN
72   245  2020  Mujeres    Todos  85.77     2023-07-02         NaN
78   266  2021  Hombres    Todos  80.82     2023-07-02         NaN
79   267  2021  Mujeres    Todos  86.51     2023-07-02         NaN
86     1  2009    Ambos    Todos  81.35     2023-07-02         NaN
87     2  2009  Hombres    Todos  78.04     2023-07-02         NaN
97    24  2010  Hombres    Todos  78.41     2023-07-02         NaN
107   45  2011    Ambos    Todos  81.91     2023-07-02         NaN
108   47  2011  Mujeres    Todos  84.81     2023-07-02         NaN
120   91  2013  Mujeres    Todos  85.13     2023-07-02         NaN
125  111  2014    Ambos    Todos  82.74     2023-07-02         NaN
135  133  2015    Ambos    Todos  82.80     2023-07-02         NaN
149  177  2017    Ambos    Todos  83.15     2023-07-02         NaN
150  178  2017  Hombres    Todos  80.18     2023-07-02         NaN
171  223  2019  Mujeres    Todos  86.10     2023-07-02         NaN
186    3  2009  Mujeres    Todos  84.30     2023-07-02         NaN
197   46  2011  Hombres    Todos  78.63     2023-07-02         NaN
218   89  2013    Ambos    Todos  82.47     2023-07-02         NaN
230  113  2014  Mujeres    Todos  85.35     2023-07-02         NaN
238  155  2016    Ambos    Todos  82.96     2023-07-02         NaN
239  156  2016  Hombres    Todos  79.97     2023-07-02         NaN
240  157  2016  Mujeres    Todos  85.56     2023-07-02         NaN
247  179  2017  Mujeres    Todos  85.75     2023-07-02         NaN
251  200  2018  Hombres    Todos  80.37     2023-07-02         NaN
266  244  2020  Hombres    Todos  80.07     2023-07-02         NaN
274  265  2021    Ambos    Todos  83.85     2023-07-02         NaN

In [ ]:
df_life.head()

   id   Año   Sexo         Distrito  Valor Fecha creacion  Fecha baja
0   6  2009  Ambos        EXTRAMURS  82.19     2023-07-02         NaN
1  10  2009  Ambos      L'OLIVERETA  80.93     2023-07-02         NaN
2  12  2009  Ambos            JESUS  81.49     2023-07-02         NaN
3  13  2009  Ambos  QUATRE CARRERES  81.33     2023-07-02         NaN
4  18  2009  Ambos         RASCANYA  81.14     2023-07-02         NaN

In [ ]:
# Creation of a class to clean data
class DataCleaner:
    def __init__(self, df):
        self.df_life = df_life

    # Drop irrelevant columns for this analysis
    def drop_columns(self, columns_to_drop):
        self.df_life = self.df_life.drop(columns=columns_to_drop)

    # Rename remaining columns for this analysis
    def rename_columns(self, new_column_names):
        self.df_life = self.df_life.rename(columns=new_column_names)

    # Remove a value from a column
    def remove_value_from_column(self, column, value_to_remove):
        self.df_life = self.df_life[self.df_life[column] != value_to_remove]

    # Change format from 'capitalized' to 'title'
    def capitalize_to_title(self, column):
        self.df_life[column] = self.df_life[column].str.title()

    def get_cleaned_df_life(self):
        return self.df_life

In [ ]:
# Process of cleaning data

cleaner = DataCleaner(df_life)

columns_to_remove = ['id', 'Sexo', 'Fecha creacion', 'Fecha baja']
cleaner.drop_columns(columns_to_remove)

cleaner.remove_value_from_column('Distrito', 'Todos')

cleaner.rename_columns({
    'Año': 'date_year',
    'Distrito': 'district',
    'Valor': 'age_expectancy',
    })

cleaner.capitalize_to_title('district')

# getting the cleaning dataset
df_life_cleaned = cleaner.get_cleaned_df_life()
df_life_cleaned.head(10)

    date_year           district  age_expectancy
0        2009          Extramurs           82.19
1        2009        L'Olivereta           80.93
2        2009              Jesus           81.49
3        2009    Quatre Carreres           81.33
4        2009           Rascanya           81.14
7        2010       Ciutat Vella           80.74
8        2010          La Saidia           82.04
9        2010    El Pla Del Real           84.08
10       2010     Camins Al Grau           82.03
11       2010  Poblats De L'Oest           81.44

In [ ]:
# Save clean data to a new CSV file
df_life_cleaned.to_csv('life_expc_vlc_cleaned.csv', sep=',', index=False)

In [ ]:
# dropping years from 2009 to 2014 as in rent dataset we only have data from 2015 to 2022
years_to_drop = [2009, 2010, 2011, 2012, 2013, 2014]
df_life_cleaned = df_life_cleaned[~df_life_cleaned['date_year'].isin(years_to_drop)]

In [ ]:
df_life_cleaned['date_year'].unique()

array([2015, 2016, 2017, 2018, 2019, 2020, 2021])

In [ ]:
# Save clean data to a new CSV file, with filtered years
df_life_cleaned.to_csv('life_cleaned_filter.csv', sep=',', index=False)